# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 404473a6490eaaca3948620ae5048f35c69676cc389d111e09c205d11ce06d01560903e916d67d718cb2972185c4e0a6728ab2052d99a3c839a8a422ca3ed2aa

test:
  secret_key_base: 76af41cb4e49301230e53f16f18943e4ce969f58554e4f621511316bb122cd6459baee4bff3ab9314a27fe78f9fda72beae8f1e97a5e03e567274f1ad6377934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
